### ISSUE TITLE
CRC labled in draft release is incorrect

### ISSUE THREAD

**Issue by tmcolby** [innotechmarine/throttle-control-module-fw-releases#6]
For example https://github.com/innotechmarine/throttle-control-module-fw-releases/releases/tag/untagged-9d72f3194ffff3ecde51
Shows `CRC=56b434f8;`  

If I download the binary and check it on my system, I see 
```bash
crc32 release.bin 
2060d47f
```

**Comment by kevinhikaruevans** [comment]
Yep, it's the crc of the firmware.bin part of the file. I could do either the release.bin or the firmware.bin, but chose the original firmware.bin because it was already implemented on the backend.

**Comment by tmcolby** [comment]
When posting the firmware to the device through the API, we need the CRC of the release.bin.  I don't see the value of including the CRC of the firmware.bin if its not used and does not represent the asset (release.bin) that is saved in this repo.  I think we should be documenting the CRC of the release.bin so that it can be directly used in the HTTP POST of that binary file to the devices without needing to manually calculate it.

**Comment by kevinhikaruevans** [comment]
Makes sense, I'll switch it over to crc the whole release.bin
